halfzebra/create-elm-app

package.json
scripts/eject.js

This PR adds async prompt support for eject script, since the trick I've been using for sync prompt is deprecated in latest versions of Node.

Reworked eject to use async prompt with promises

---

template/README.md

Closes #12 
Adds documentation on how to use npm JS libraries to the `template/README.md`

Add docs for using npm JS packages

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json

Vendor prefix the css as well as extract it into it's own stylesheet on
build. Taken from create-react-app webpack config.

Add Autoprefixer to CSS output from Webpack

---

package.json

So linting works immediately when you clone locally.

Add ESLint as a dev dep

---

.gitignore
bin/global-cli.js

Closes #44 
If child process return non zero exit status, main process exits with it status as well.
Make small refactoring.
I'm working on tests for the case

Return exit code from spawned process in run scripts

---

scripts/create.js

Hi!
I've used this tool a couple times but each time I did I ended up having to go back to the GitHub repository in order to find the command `elm-app start`.  I thought it would be nice to have parity with `create-react-app`'s initialization message.
Let me know if some of the copy isn't exactly right, for instance, "Removes this tool and copies build dependencies, configuration files and scripts into the app directory" might not be exactly what `elm-app eject` does.
Also, I didn't see any issues for this so it might not be a big enough deal to warrant a change. Don't hesitate to close this PR if you're not interested :)
Cheers!
EDIT:
Here is a screenshot so you don't have to rummage around in a local build to check it out:

Add getting started instructions to create script.

---

config/webpack.config.dev.js

I tried to start app with debug flag after updating to elm 0.18 but there was a missing flag in webpack dev configuration. This PR adds it

Add debug flag to be used with elm 0.18 debugger

---

.eslintrc
tests/create-elm-app.spec.js
tests/elm-app.build.spec.js

Due to fixes in #62  like
https://github.com/halfzebra/create-elm-app/pull/62/commits/3940a1fa212eb781db7ab25effe833fcc8f3f49f#diff-26656f8f2b440480d38c7ded4bafa17cR20
https://github.com/halfzebra/create-elm-app/pull/62/commits/3940a1fa212eb781db7ab25effe833fcc8f3f49f#diff-26656f8f2b440480d38c7ded4bafa17cR37
have added `array-bracket-spacing` and `computed-property-spacing` rules.
P.S. I think it's uncommon code style.

Add few eslint rules to validate bracket spacing

---

scripts/start.js

This is one tweak that makes apps with client side routing (common for an elm app) work when F5 is pressed. A tiny config change which seems to have little downside. Seems a shame to have to eject just to add this. 
Understand if you feel like this is something that should not be on by default.

enabled history api fallback on the web pack dev server

---

bin/create-elm-app-cli.js

`create-elm-app` crashed out-of-the-box after installing with `yarn global add create-elm-app`, at least on yarn 0.19.1. This was due to the fact that yarn had installed the `elm` package alongside `create-elm-app` rather than in the expected `create-elm-app/node_modules`.
Fixes #90

fix(cli): Fix crash when installed via yarn

---

bin/elm-app-cli.js

This is the same bug as was with the create-elm-app cli. `elm-app` crashes if it's been installed with yarn.

fix(cli): Fix crash in elm-app installed with yarn

---

template/tests/Tests.elm

App.init takes the logo path, which should also be provided in the tests, see:
https://github.com/halfzebra/create-elm-app/issues/98

fix(elm test) (#98) Fixed an elm type error in tests.

---

tests/cliAccessibility.js
tests/elm-app.build.spec.js
tests/elm-app.test.spec.js

Just add tests for `elm-app test` command to avoid issues like #110

test(elm-app test): Add tests for 'elm-app test' command

---

template/README.md
template/src/index.js

Forgot to rename main module name in index.js during refactoring #110
Closes #114

fix(index.js): Fix running application

---

template/tests/Tests.elm

The expected value should come first and the actual value second.

Template: Tests.elm: Expectation argument order

---

template/README.md

To address https://github.com/halfzebra/create-elm-app/issues/120, adding a heads-up for installing packages for tests.

docs(readme) Write about installing packages in tests

---

README.md
template/README.md

In #135 the folder structure changed and the docs on README.md did too,
but not the ones on the template README.
This commit fixes the folder structure section.

Fix folder structure in the template docs

---

config/webpack.config.dev.js

`!!process.env.ELM_DEBUGGER` is default to `false`, and any string will parse to `true`, even `"false"`, contradicting the documented behavior.
This PR fixes how the string is parsed from the command line to default to `true`, and make `"false"` disable the debugger.
**Edited for correctness**
---
With the last version it seems like the debugger is turned off by
default and it can be enabled with the ELM_DEBUGGER env variable.
Not sure if that was the intention but it is the behavior, so this updates the docs. \
Maybe the default on `elm-app start` should actually default to debugger true. Feel free to close if so.

Fix ELM_DEBUGGER parsing

---

template/README.md

*Create React App* and `npm run build` were mentioned. This swaps them for *Create Elm App* and `elm-app`.
There is also some mentions of react-scripts and *Create react app* in the github pages deploy section of the docs. Not sure how valid that section is tho, so I didn't touch them.

docs: Change refs to React and npm with Elm and elm-app

---

config/paths.js

Defines the base path of `.env` files in `config/paths.js`. This definition is referenced by `config/env.js`, which sets up the environment variables before starting or building with create-elm-app.

Add .env file path to paths config

---

template/tests/Tests.elm

This import is already in the Elm prelude.

Tests.elm: Remove 'import String'

---

README.md
config/webpack.config.prod.js
package.json
template/README.md
template/public/index.html
template/public/manifest.json
template/src/index.js
template/src/registerServiceWorker.js
yarn.lock

This PR enables us to deploy apps as Progressive Web Apps.
Added SWPrecacheWebpackPlugin and a service worker to serve assets from the local cache.
@fobos @gyzerok @jackfranklin got an opinion?
I just have been to the conference, and I think this is what we should support.
Here's an example of working PWA in Elm that I've made yesterday https://halfzebra.github.io/elm-scrum-cards-pwa/

feat($build): Added the support for PWA

---

config/env.js
config/webpack.config.dev.js
config/webpack.config.prod.js
config/webpackDevServer.config.js
package.json
scripts/utils/webpackHotDevClient.js
template/README.md
template/src/registerServiceWorker.js
tests/build.spec.js
tests/cliAccessibility.js
tests/create-elm-app.spec.js
tests/elm-app.build.spec.js
tests/elm-app.eject.spec.js
tests/elm-app.test.spec.js
yarn.lock

Upgrade dependencies and introduce unexpectedjs

---

scripts/eject.js

This will copy the webpackHotDevClient.js so ejecting works.

fix: Copy the whole utils folder

---

tests/elm-app.eject.spec.js

This PR add tests that checks that `scripts/utils/formatElmCompilerErrors.js` and `scripts/utils/webpackHotDevClient.js` exists.

test: Add utility scripts test

---

template/README.md

As discussed in #161, I added a chapter of how to use custom environment variables. Hope it's fine this way, looking forward to hear from you!

docs: add documentation about usage of custom environment variables

---

template/README.md

When following the instructions from the User Guide, I got stuck briefly on the `gh-pages` step. This fixes the instructions so that it's more clear how the user should obtain the `gh-pages` program if they don't already have it.

docs: improve deploy instructions for GitHub Pages

---

config/webpack.config.prod.js

In production mode, debugger is disabled by default.

Fix comment

---

README.md

This PR is a followup on #14 
The readme part is heavily inspired by https://github.com/facebookincubator/create-react-app/. 
One part that I had to add is about creating the `package.json` file. Since there does not exist one after creating the project.

Add Readme chapter for adding a CSS Preprocessor

---

scripts/build.js

Default behaviour has not been changed, `NODE_ENV` is still production if not set.
Can verify with 
```
$ elm-app build # still uses .env.production
$ NODE_ENV=production elm-app build # uses .env.production
$ NODE_ENV=test elm-app build # uses .env.test
```
Fixes issiue #180

added the ability to set environment when running build

---

config/webpackDevServer.config.js

`setup` was deprecated in webpack/webpack-dev-server#1108

config/webpackDevServer.config.js: Fix deprecation warning

---

template/README.md

Add a section to the user guide that explains how to host apps at other paths than server root
I was deploying my first elm app last week, it had to be served at `/admin` and I remembered that create-react-app had an option for this, but I couldn't find it here so after confirming that it does work with create-elm-app as well I copied it hoping that it may be useful for other people.

docs: Add "Building for Relative Paths" section

---

template/README.md

I've added documentation for running development server on HTTPS, which is already implemented in the [scripts/start.js](https://github.com/halfzebra/create-elm-app/blob/39cda7b946182d2109027dd094a95662da7acf49/scripts/start.js#L156).

added documentation for using HTTPS in development

---

template/README.md

```elm
// The comment looked
// a little strange.
```

docs(template/README.md): Fix multi-line comment in Elm code block

---

.gitignore
package.json

`.gitignore` was ignoring some items under template that still appeared in the packaged releases,
because `template` was explicitly included in package.json, and that overrides those ignores.
Both the 2.0.0-rc1 and 2.0.0-rc2 releases included stray build products.
Adding explicit exclusions for the build products under `template` to `package.json` prevents
packaging errors.
I've added `template/elm-stuff` and `template/index.html` to `.gitignore` too, because those
are created if `elm make src/Main.elm` is run in `template`, which seems to have been the cause.
verified the changes by using `rm *.tgz; (cd template; elm make src/Main.elm); npm pack`, and inspecting the list of files packed.
re #275

fix: exclude build products under template from packaging

---

bin/elm-app-cli.js
config/paths.js

Fixing #289 
Updating how to get the path for `elm` command so that it works also as a local dev dependency.

Making `create-elm-app` work also as a local dev dependency

---

config/webpack.config.prod.js
scripts/build.js

fix: Makes it possible to enable the Elm debugger with ELM_DEBUGGER=true

---

config/webpack.config.prod.js

Hi!
First of all, thank you for this project. It has a great set of features and for that reason it is the starting point for my current app.
Regarding browser compatibility, I spent a few hours trying to figure out why the code would work in Internet Explorer 11 (IE11) in development but not in production mode.
ES5 is required in the minified code if you want compatibility with IE11.
As it turns out, even though Babel makes ES5 code, you need to make UglifyJS export ES5 code as well after minification, otherwise an object like `{$:3,n:n,p:r}` gets abbreviated to `{$:3,n,p:r}` using [ES6 object-shorthand syntax](https://eslint.org/docs/rules/object-shorthand).

Make minified code compatible with IE11

---

config/webpack.config.prod.js
template/README.md
tests/create-elm-app.spec.js

This PR addressed the changed discussed in #314. There might be still room in terms of shaving some bytes off, but this looks fine so far. I basically did comparisons to make sure we're not moving in the wrong direction.
```shell
17.280 as  1 Nov 21:50 main.516c338b.chunk.js
110.583 as  1 Nov 21:54 main.516c338b.chunk.js 
17.289 as  1 Nov 21:55 main.516c338b.chunk.min.js
29.660 as  1 Nov 22:20 main.9e0ba63c.chunk.js
17.876 as  1 Nov 22:21 main.9e0ba63c.chunk.js
```
* Removes `DEAD_CODE_ELIMINATION` env
* Changed chapter in docs
* Sourcemaps disabled by default in prod build
* Uglify settings
* Based on elm docs
* 2 Passes
* Build application and executed it
* Ran `npm run test`
Solves #314

Uglifyjs configuration for elm 0.19

---

config/webpack.config.dev.js
config/webpack.config.prod.js

The pull requests adds the runtime opts. With tests I couldn't see a difference.
I tried to benchmark the changes on an application, but I don't know a large codebase with `create-elm-app`. The applications I have are fast, and with webpack and uglify and other parts of the build, I can't tell a difference with and without the arguments. So either there is no noticeable difference, they're not configured correctly or the difference will show with a larger codebase.
Ran the total optimized build a 100 times and got 7.7 minutes before, and 7.5 minutes with the changes. Could be measurement errors.
Is it possible to release it as `beta`/`next`/`rc` to try it on real world projects?
I wouldn't add the configuration if there the difference is not proven.
Potentially solves #321

Runtime opts to improve build speed 

---

config/webpack.config.dev.js
config/webpack.config.prod.js

The feature to pass compiler flags is hardly documented. A test of
`node-elm-compiler` is passing the argument in form of an array. Hence
the change from string to string array.
<https://github.com/rtfeldman/node-elm-compiler/blob/48f29fc243e149ad6f8ee0c6ef740d998764cf55/test/compile.js#L57>
Added a change to `elm-webpack-loader`, too.
https://github.com/elm-community/elm-webpack-loader/pull/161

Passing rts options argument as array

---

scripts/utils/formatElmCompilerErrors.js

Hello,
I'm not sure if this only happens on Windows 10, but the error overlay in the browser on compilation failure looks e.g. like this
```
Error: Compiler process exited with error Compilation failed
[                                                  ] - 1 / 74
[=                                                 ] - 2 / 74
[==                                                ] - 3 / 74
[==                                                ] - 4 / 74
[===                                               ] - 5 / 74
[====                                              ] - 6 / 74
...
[===============================================   ] - 70 / 74
[===============================================   ] - 71 / 74
```
Which is why I changed the rule on line 21 to match not only …

fix: strip compilation progress bar on Windows

---

template/README.md

Greetings! Just a simple documentation patch.

Fix rogue `"` in gh-pages instructions

---

config/webpack.config.dev.js
config/webpack.config.prod.js

Adding a scss or sass handler conflicts with the URL-loader, which produces a weird error message. Ignoring scss and sass files in the first place allows adding a scss loader without ejecting the web pack config (and then applying the fix in this pull request). 
Best, 
ambiso

Ignore scss and sass files for url-loader

---

template/README.md

Fix removed webpack documentation:

Fix webpack safe-write link in guide

---

bin/elm-app-cli.js
scripts/start.js
template/README.md

- No default behavior has changed
- An optional `--no-browser` flag has been added to the `start` command that prevents opening the browser automatically
- An optional `--help` flag has been added to the `start` command which displays help for the `start` command
- The `help` function in `elm-app-cli.js` has been refactored to be able to provide additional help messages for other commands

feat: Add `--no-browser` flag to `start` command

---

config/webpack.config.prod.js
package.json
scripts/build.js
template/README.md

A week too early for [Hacktoberfest](https://hacktoberfest.digitalocean.com/), but this removes the [deprecated sw-precache](https://github.com/GoogleChromeLabs/sw-precache#%EF%B8%8F-sw-precache-%EF%B8%8F), and instead adds the [workbox-webpack-plugin](https://www.npmjs.com/package/workbox-webpack-plugin).
It's a fairly minimal change, but here's a screenshot:
I also added [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin), because there can be problems with workbox picking up assets not handled by webpack.
Would be happy to hear your thoughts! 😊

Add workbox

---

config/webpack.config.prod.js
package.json

I ran `npm audit` on the current master, and got the following output:
```
create-elm-app$ npm i && npm i --package-lock-only && npm audit
[...]
added 274 packages from 176 contributors, removed 22 packages, updated 13 packages and audited 33377 packages in 23.756s
found 9 vulnerabilities (1 low, 1 moderate, 7 high)
run `npm audit fix` to fix them, or `npm audit` for details
npm WARN deprecated fsevents@1.2.4: Way too old
npm notice created a lockfile as package-lock.json. You should commit this file.
added 67 packages from 25 contributors and audited 33377 packages in 11.444s
found 9 vulnerabilities (1 low, 1 moderate, 7 high)
run `npm audit fix` to fix them, or `npm audit` for details
=== npm audit security report === …
```

Update insecure dependencies

---

package.json

If there is no reason against it that I'm not aware of, this can be merged back to use the base repository of `elm-webpack-loader`.
fix #373

refactor(package.json): elm-webpack-loader 6.0.0 instead of fork

---

package.json

Bumped elm-hot-webpack-loader to v1.1.5 to address "Cannot read property \'hasOwnProperty\' of
undefined" error w/ elm/browser 1.0.2

fix(package.json): bumped elm-hot-webpack-loader to v1.1.5

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json

Resolves paths to assets in strings in Elm code with webpack.
Example:
```
img [ src "require:src/assets/logo.svg" ] []
```
Fixes #363
Documentation not part of this PR.

feat(webpack config): elm-webpack-asset-loader to require assets

---

.travis.yml
config/webpack.config.dev.js
config/webpack.config.prod.js

Hello ! I was having trouble importing a module that depended on another mjs module.
I corrected this by `elm-app eject` and making those two changes.
Maybe we could add them back to the main repo and share with everyone !
It would also make me able to revert my `eject` and use the create-elm-app as is again.

Also resolve mjs modules

---

package.json

Change updates a transitive dependency for security reasons recommended by github
Going with `^` for conistency with other versions

Update elm-asset-webpack-loader version

---

bin/elm-app-cli.js
tests/elm-app.create.spec.js

fix(bin/elm-app): pass the correct argument to `elm-app create` command

---

config/webpack.config.dev.js
config/webpack.config.prod.js
config/webpackDevServer.config.js
template/README.md
template/public/index.html

Remove the `shortcut` link type in `<link rel="shortcut icon" ...>`.
From [this MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types):
> The shortcut link type is often seen before icon, but this link type is non-conforming, ignored and **web authors must not use it anymore**.

fix: remove the `shortcut` link type

---

config/webpack.config.dev.js
config/webpack.config.prod.js

This should fix  #438 
It happened that weback select for .mjs url-loader instead of babel-loader.
I have also updated the syntax for the webpack configuration that switched from `query` to `options`

Fixed failed import of .mjs files
