- .eslintrc
- .gitignore
- .travis.yml
- CHANGELOG.md
- README.md
- bin/global-cli.js
- package.json
- scripts/build.js
- scripts/create.js
- scripts/eject.js
- scripts/start.js
- template/README.md
- template/gitignore
- tests/ci.js
This PR aims to close #4 
It also has some bug-fixes and bumps the version.
> Automated tests

- config/webpack.config.dev.js
- config/webpack.config.prod.js
- package.json
Hello,
Cool project!
This PR allows fonts and images to be imported through webpack.
I just copied [what create-react-app did](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js) for this.
This allows people to use font-awesome, background images in CSS, etc. 😄
> Add support for images and fonts

- scripts/create.js
- tests/ci.js
`elm-package.json` was missing a reference to `src` folder.
> Add src folder

- scripts/eject.js
Add missing script to ejected `package.json`
> Added script for testing after ejecting

- template/src/index.js
Just a small extra space I noticed!
> Delete extra space in index.js

- config/webpack.config.dev.js
- package.json
- scripts/start.js
- template/src/App.elm
From now on this project relies on [react-dev-utils](https://www.npmjs.com/package/react-dev-utils)
> Add react dev utils

- package.json
> Added missing dependency and bump the version

- template/src/App.elm
- template/tests/Tests.elm
- template/tests/elm-package.json
Message moved to `model`.
Added 1 test.
> Make message part of model

- tests/ci.js
- tests/data/Main.elm
Add test case for checkin non zero status code during `elm-app build`.
Cleanup tests
Move down all helpers functions
> Add test case with returning non zero exit codes

- package.json
- template/elm-package.json
- template/src/Main.elm
Tests pass and it works with my app.
Thank you!
> Upgrade Elm to 0.18

- CHANGELOG.md
- package.json
> Release 0.2.0

- .travis.yml
- CHANGELOG.md
- bin/elm-app-cli.js
- package.json
- tests/elm-app.eject.spec.js
> New release

- scripts/start.js
> Add `historyApiFallback: true` to webpack-dev-server

- config/webpack.config.dev.js
- config/webpack.config.prod.js
- package.json
- template/README.md
- template/src/App.elm
- template/src/Main.elm
- template/src/index.js
- template/src/logo.svg
- template/src/main.css
> Replace file loader

- template/README.md
- yarn.lock
> docs(readme): Fix anchor to Installing JavaScript packages chapter

- template/README.md
Submitting PR for Issue #119 
Thanks
> Documenting proxy setting for elm-app

- template/README.md
> docs: Add missing documentation about importing the stylesheets

- config/webpack.config.dev.js
- template/README.md
* Add some explicit docs about how to set the env var to modify the PUBLIC_URL
* Remove stale PUBLIC_PATH references in docs and comments
> Document usage of PUBLIC_URL as an environment variable

- template/README.md
Fix a typo in `template/README.md`
> docs(template/README.md): Fix a typo

- package.json
- yarn.lock
to fix rtfeldman/node-test-runner#219
> Upgrade elm-test

- package.json
> ci: Fix the release script

- README.md
- appveyor.yml
> Setup appveyor

- README.md
> chore: Fix the badge link

- README.md
- template/README.md
> docs: Move the docs about setting up SASS to User Guide

- config/webpack.config.prod.js
The condition got changed in #197, but the comment wasn't.
> Tweak a comment in webpack.config.prod.js

- template/README.md
Minor typo (only one I spotted)
> Fix minor README.md typo

- template/README.md
> Added JavaScript Interoperation example

- README.md
> docs: Update docs to include ELM spa example using CEA

- template/README.md
> Fix typo in template/README.md

- template/README.md
Hello! Thanks for the tool—I started playing with it recently, and I can't imagine a simpler setup process. This PR just fixes a tiny typo I notices while reading the docs.
> Typo: comand -> command

- template/README.md
The readme example showing how autoprefixer worked was both wrong and misleading. I changed the example so that it was both correct and more understandable.
> Fixed autoprefixer example

- template/README.md
Hi there, I use your project extensively and I love it!
I think there's a tiny mistake on this line in the readme.
> Fix homepage recommendation

- template/README.md
This PR makes a some markdown changes based on `markdownlint` suggestions. Some changes were perhaps meant to be like they were before and can be discussed (e.g. the image is now integrated via markdown, instead of html)
Fixes #258
> README template markdown fixes

- template/README.md
Updated the User Guide to include a link to our Slack channel.
> docs(template/README.md): Added a link to our slack channel.

- template/README.md
Added a single line to instruct a developer on how to change the port of the listening server
> docs(template/README.md): Change Port

- config/webpack.config.dev.js
- package.json
- scripts/create.js
- template/src/Main.elm
- template/src/index.js
- tests/build.spec.js
- tests/cliAccessibility.js
- tests/create-elm-app.spec.js
- tests/elm-app.build.spec.js
- tests/elm-app.eject.spec.js
- tests/elm-app.test.spec.js
> 0.19 tests

- .travis.yml
- package.json
> fix(package.json): Upgrade elm-test to fix errors on Node v10

- package.json
> fix(package.json): Upgrade elm-test to 0.19.0-beta8

- template/README.md
> Add netlify deployment description to readme

- config/webpack.config.prod.js
> fix(webpack.config.prod): Disable Webpack performance tips for prod config

- template/README.md
> Update port docs

- scripts/create.js
> fix(create): Fixed a bug that did not allow creating apps with numeric names

- scripts/create.js
> fix(create): Fix creation problems on Windows

- template/README.md
> docs: Added the documentation on overriding Webpack configs.

- package.json
> chore: Upgraded development dependencies

- CONTRIBUTING.md
- README.md
- config/paths.js
- config/webpack.config.dev.js
- config/webpack.config.prod.js
- config/webpackDevServer.config.js
- template/README.md
- template/src/main.css
A release with a breaking change for proxy configuration, addresses #326, #320, #251
> Major release

- config/paths.js
- config/webpackDevServer.config.js
- template/elmapp.config.js
> fix: Fix setupProxy configuration option

- template/elm.json
This allows latest elm/http to be picked up by app
initialised with create-elm-app command
Closes #333
> fix(template/elm.json): Bump latest versions of elm core

- package.json
> Upgrade to Elm 0.19.0-bugfix6

- bin/elm-app-cli.js
- package.json
- tests/elm-app.test.spec.js
> fix: test script by changing the way it resolves the path to elm binary

- package.json
> fix: add @babel/runtime and upgrade all babel dependencies

- scripts/eject.js
> Minor spelling correction for ejection warning.

- template/README.md
Hey there,
I banged my head for a while this morning on how to use environement variables. Read the guide but was getting undefined all over the place.
This until I realized that those changes are not picked up by the dev-server.
So I simply added a short note to indicate that work on the .env file need an elm-app restart.
Cheers!
> Changes to .env require a elm-app restart

- template/elm.json
- Upgrading elm browser in order to use the new UI for the debugger
- Upgrading elm core to have some bug fixings
> Upgrade elm/browser and elm/core

- README.md
> Adding elm-boil as alternative

- config/webpack.config.dev.js
- config/webpack.config.prod.js
> fix(config): specify core-js version to avoid printing warnings

- renovate.json
> ci(renovate.json): automerge patch fixes for dev deps

- template/README.md
https://github.com/chimurai/http-proxy-middleware#tldr
> Update proxy configuration docs

- renovate.json
> ci: mark major dependency update as a breaking change in renovate PRs

- template/README.md
> Fix grammar

- template/README.md
> Caught instead of called?
